services:
  sqlserver-arraycms:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-arraycms
    environment:
      SA_PASSWORD: "P@ssw0rd123"
      ACCEPT_EULA: "Y"
    ports:
      - "1534:1433"  
    volumes:
      - /var/opt/mssql/data:/var/opt/mssql/data

  arraycms-web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: arraycms-web
    ports:
      - "5101:8080"
    depends_on:
      - sqlserver-arraycms
    networks:
      - default

volumes:
  sqlserverdata:
